baseURL = "www.example.com"
languageCode = "en-us"
title = "Garza Family Lawn Care. Great Service at a Great Price."

[params]
  # In most cases you will only want to use either one of these. If you have Google Analytics included in your GTM tags don't put your GA ID here. Otherwise your data might be useless.
  google_analytics_id = ""
  google_tag_manager_id = ""

  [params.homepage]
    show_call_box = true

  [params.logo]
    mobile = "images/logo/garza.png"
    desktop = "images/logo/garza.png"
    desktop_height = "80px"
    alt = "Garza Family Lawn Care"

  [params.homepage_meta_tags]
    meta_description = "Call us for Mowing, Blower Cleanup, Power Washing, Junk Cleanups, Fencing Repairs, Hauls, Acres, etc!"
    meta_og_title = "Garza Family Lawn Care - Austin yard and landscape services"
    meta_og_type = "website"
    meta_og_url = "https://garzafamilylawns.netlify.app"
    meta_og_image = "https://garzafamilylawns.netlify.app/images/illustrations/garza-social.png"
    meta_og_description = "Call us for Mowing, Blower Cleanup, Power Washing, Junk Cleanups, Fencing Repairs, Hauls, Acres, etc!"
    meta_twitter_card = "summary"
    meta_twitter_site = "@garzafamilylawncare"
    meta_twitter_creator = "@garzafamilylawncare"

  [garzafamilylawncarearams.footer]
    copyright_text = 'Garza Family Lawn Care 2020'

[menu]
  # Main Menu
  [[menu.main]]
    name = "Services"
    url = "/services/"
      weight = 1

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
      weight = 1

  [[menu.footer]]
    name = "Contact"
    url = "/contact/"
      weight = 2
